In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [24]:
from sklearn.datasets import load_digits
digits = load_digits()

Data load, 데이터 파악

In [25]:
print("Feature names:\n", digits['feature_names'])
print("Target names:", digits['target_names'])

Feature names:
 ['pixel_0_0', 'pixel_0_1', 'pixel_0_2', 'pixel_0_3', 'pixel_0_4', 'pixel_0_5', 'pixel_0_6', 'pixel_0_7', 'pixel_1_0', 'pixel_1_1', 'pixel_1_2', 'pixel_1_3', 'pixel_1_4', 'pixel_1_5', 'pixel_1_6', 'pixel_1_7', 'pixel_2_0', 'pixel_2_1', 'pixel_2_2', 'pixel_2_3', 'pixel_2_4', 'pixel_2_5', 'pixel_2_6', 'pixel_2_7', 'pixel_3_0', 'pixel_3_1', 'pixel_3_2', 'pixel_3_3', 'pixel_3_4', 'pixel_3_5', 'pixel_3_6', 'pixel_3_7', 'pixel_4_0', 'pixel_4_1', 'pixel_4_2', 'pixel_4_3', 'pixel_4_4', 'pixel_4_5', 'pixel_4_6', 'pixel_4_7', 'pixel_5_0', 'pixel_5_1', 'pixel_5_2', 'pixel_5_3', 'pixel_5_4', 'pixel_5_5', 'pixel_5_6', 'pixel_5_7', 'pixel_6_0', 'pixel_6_1', 'pixel_6_2', 'pixel_6_3', 'pixel_6_4', 'pixel_6_5', 'pixel_6_6', 'pixel_6_7', 'pixel_7_0', 'pixel_7_1', 'pixel_7_2', 'pixel_7_3', 'pixel_7_4', 'pixel_7_5', 'pixel_7_6', 'pixel_7_7']
Target names: [0 1 2 3 4 5 6 7 8 9]

In [26]:
print(digits['data'].shape)
print(digits['target'].shape)

(1797, 64)
(1797,)

In [27]:
df = pd.DataFrame(digits.data, columns = digits.feature_names)
df['target'] = digits.target
df

,pixel_0_0,pixel_0_1,pixel_0_2,pixel_0_3,pixel_0_4,pixel_0_5,pixel_0_6,pixel_0_7,pixel_1_0,pixel_1_1,...,pixel_6_7,pixel_7_0,pixel_7_1,pixel_7_2,pixel_7_3,pixel_7_4,pixel_7_5,pixel_7_6,pixel_7_7,target
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0,0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0,1
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0,2
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0,3
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1792,0.0,0.0,4.0,10.0,13.0,6.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,2.0,14.0,15.0,9.0,0.0,0.0,9
1793,0.0,0.0,6.0,16.0,13.0,11.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,16.0,14.0,6.0,0.0,0.0,0
1794,0.0,0.0,1.0,11.0,15.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.0,9.0,13.0,6.0,0.0,0.0,8
1795,0.0,0.0,2.0,10.0,7.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,5.0,12.0,16.0,12.0,0.0,0.0,9
1796,0.0,0.0,10.0,14.0,8.0,1.0,0.0,0.0,0.0,2.0,...,0.0,0.0,1.0,8.0,12.0,14.0,12.0,1.0,0.0,8

In [28]:
from sklearn.model_selection import train_test_split
X_train1, X_test, y_train1, y_test = train_test_split(digits.data, digits.target, random_state = 0)
X_train, X_val, y_train, y_val = train_test_split(X_train1, y_train1, random_state = 0)

In [29]:
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_val shape:", X_val.shape)
print("y_val shape:", y_val.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

X_train shape: (1010, 64)
y_train shape: (1010,)
X_val shape: (337, 64)
y_val shape: (337,)
X_test shape: (450, 64)
y_test shape: (450,)

In [30]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

데이터 전처리

In [31]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

Decision Tree Classifier

Hyperparmeter: max_depth, min_samples_leag, max_leaf_nodes

In [32]:
training_accuracy = []
val_accuracy = []
max_depth = []
min_samples_leaf = []
max_leaf_nodes = []

md_settings = [10, 100, 1000]
msl_settings = [1, 10, 100]
mln_settings = [10, 100, 1000]

for md in md_settings:
    for msl in msl_settings:
        for mln in mln_settings:
        # model training with labeled training data
            dt = DecisionTreeClassifier(max_depth = md, min_samples_leaf = msl, max_leaf_nodes= mln, random_state=0)
            dt.fit(X_train, y_train)

        # prediction
            y_train_hat = dt.predict(X_train)
            y_val_hat = dt.predict(X_val)

        # evaluation    
            training_accuracy.append(accuracy_score(y_train, y_train_hat))
            val_accuracy.append(accuracy_score(y_val, y_val_hat))
            max_depth.append(md)
            min_samples_leaf.append(msl)
            max_leaf_nodes.append(mln)

result_dt = pd.DataFrame({"max_depth": max_depth, "min_samples_leaf": min_samples_leaf, "max_leaf_nodes": max_leaf_nodes, "training accuracy": training_accuracy, "val accuracy": val_accuracy})
result_dt

,max_depth,min_samples_leaf,max_leaf_nodes,training accuracy,val accuracy
0,10,1,10,0.698020,0.694362
1,10,1,100,0.988119,0.804154
2,10,1,1000,0.995050,0.801187
3,10,10,10,0.698020,0.694362
4,10,10,100,0.870297,0.792285
5,10,10,1000,0.870297,0.792285
6,10,100,10,0.636634,0.646884
7,10,100,100,0.636634,0.646884
8,10,100,1000,0.636634,0.646884
9,100,1,10,0.698020,0.694362
10,100,1,100,0.988119,0.804154
11,100,1,1000,1.000000,0.798220
12,100,10,10,0.698020,0.694362
13,100,10,100,0.870297,0.792285
14,100,10,1000,0.870297,0.792285
15,100,100,10,0.636634,0.646884
16,100,100,100,0.636634,0.646884
17,100,100,1000,0.636634,0.646884
18,1000,1,10,0.698020,0.694362
19,1000,1,100,0.988119,0.804154
20,1000,1,1000,1.000000,0.798220
21,1000,10,10,0.698020,0.694362
22,1000,10,100,0.870297,0.792285
23,1000,10,1000,0.870297,0.792285
24,1000,100,10,0.636634,0.646884
25,1000,100,100,0.636634,0.646884
26,1000,100,1000,0.636634,0.646884

SVM

Hyperparmeter: C, gamma

In [33]:
training_accuracy = []
val_accuracy = []

C_settings = [0.01, 0.1, 1, 10, 100]
gamma_settings = [0.01, 0.1, 1, 10, 100]
for C in C_settings:
    for gamma in gamma_settings:
        # model training with labeled training data
        svc = SVC(C = C, gamma = gamma, random_state = 1)
        svc.fit(X_train_scaled, y_train)

        # prediction
        y_train_hat = svc.predict(X_train_scaled)
        y_val_hat = svc.predict(X_val_scaled)

        # evaluation    
        training_accuracy.append(accuracy_score(y_train, y_train_hat))
        val_accuracy.append(accuracy_score(y_val, y_val_hat))

result_svm = pd.DataFrame({"C":sorted(C_settings*5), "gamma":gamma_settings*5, "training accuracy": training_accuracy, "validation accuracy": val_accuracy})
result_svm

         C   gamma  training accuracy  validation accuracy
0     0.01    0.01           0.110891             0.080119
1     0.01    0.10           0.110891             0.080119
2     0.01    1.00           0.110891             0.080119
3     0.01   10.00           0.110891             0.080119
4     0.01  100.00           0.110891             0.080119
5     0.10    0.01           0.939604             0.946588
6     0.10    0.10           0.237624             0.216617
7     0.10    1.00           0.110891             0.080119
8     0.10   10.00           0.110891             0.080119
9     0.10  100.00           0.110891             0.080119
10    1.00    0.01           0.996040             0.976261
11    1.00    0.10           1.000000             0.940653
12    1.00    1.00           1.000000             0.112760
13    1.00   10.00           1.000000             0.080119
14    1.00  100.00           1.000000             0.080119
15   10.00    0.01           1.000000             0.979228
16   10.00    0.10           1.000000             0.937685
17   10.00    1.00           1.000000             0.112760
18   10.00   10.00           1.000000             0.080119
19   10.00  100.00           1.000000             0.080119
20  100.00    0.01           1.000000             0.979228
21  100.00    0.10           1.000000             0.937685
22  100.00    1.00           1.000000             0.112760
23  100.00   10.00           1.000000             0.080119
24  100.00  100.00           1.000000             0.080119

RandomForesrClassifier

Hyperparmeter: n_estimators

In [34]:
training_accuracy = []
val_accuracy = []

n_settings = [1, 5, 10, 15, 50, 100]

for n in n_settings:
    # model training with labeled training data
    rf = RandomForestClassifier(n_estimators = n, random_state = 2)
    rf.fit(X_train_scaled, y_train)

    # prediction
    y_train_hat = rf.predict(X_train_scaled)
    y_val_hat = rf.predict(X_val_scaled)

    # evaluation
    training_accuracy.append(accuracy_score(y_train, y_train_hat))
    val_accuracy.append(accuracy_score(y_val, y_val_hat))

pd.DataFrame({"n_estimators": n_settings, "training accuracy": training_accuracy, "validation accuracy": val_accuracy})

   n_estimators  training accuracy  validation accuracy
0             1           0.902970             0.774481
1             5           0.993069             0.913947
2            10           0.999010             0.940653
3            15           0.999010             0.952522
4            50           1.000000             0.973294
5           100           1.000000             0.970326

최적의 learning algorithm 선택
hyperparameter
DecisionTree: max_depth = 10, min_samples_leaf = 1, max_leaf_nodes= 100
SVM: C = 10, gamma = 0.01
RandomForest: n_estimators = 50

In [35]:
dt = DecisionTreeClassifier(max_depth = 10, min_samples_leaf = 1, max_leaf_nodes= 100)
svc = SVC(C = 10, gamma = 0.01)
rf = RandomForestClassifier(n_estimators = 50)

dt.fit(X_train, y_train)
svc.fit(X_train_scaled, y_train)
rf.fit(X_train_scaled, y_train)

y_test_hat_dt = dt.predict(X_test)
y_test_hat_svc = svc.predict(X_test_scaled)
y_test_hat_rf = rf.predict(X_test_scaled)

print("evaluation of Decision Tree: {:.2f}" .format(accuracy_score(y_test, y_test_hat_dt)))
print("evaluation of SVM: {:.2f}" .format(accuracy_score(y_test, y_test_hat_svc)))
print("evaluation of Random Forest: {:.2f}" .format(accuracy_score(y_test, y_test_hat_rf)))

evaluation of Decision Tree: 0.85
evaluation of SVM: 0.98
evaluation of Random Forest: 0.97